homeassistant:
  #  Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 42.8731
  longitude: -71.3904
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 108
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York


#HTTP Settings
http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password

#Hue Lights Setup
light:
  - platform: hue
    host: 192.168.11.161

  - platform: mqtt
    name: 'Brendan Bedroom TV Light'
    state_topic: '/lights/brendanbedroom/tvlight/light/status'
    command_topic: '/lights/brendanbedroom/tvlight/light/switch'
    brightness_state_topic: '/lights/brendanbedroom/tvlight/brightness/status'
    brightness_command_topic: '/lights/brendanbedroom/tvlight/brightness/set'
    rgb_state_topic: '/lights/brendanbedroom/tvlight/rgb/status'
    rgb_command_topic: '/lights/brendanbedroom/tvlight/rgb/set'
    brightness_scale: 100
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
#Group setups
group: !include groups.yaml  

#scene setups
scene: !include scenes.yaml
script: !include_dir_merge_named scripts/
mqtt:
  broker: 192.168.11.160
  port: 1883
  client_id: home-assistant-1      
      
binary_sensor:
  - platform: mqtt
    name: "Bedtime Switch"
    state_topic: "/dash/bedtime_button"
    payload_on: "active"
    payload_off: "inactive"

switch: !include switch.yaml   
input_select:
  brendan_bedroom_active_media_player:
    name: Bedroom Active Player
    options:
     - Roku
     - Kodi
     - Chromecast
    initial: Roku
automation:
  - alias: "Bedtime Trigger"
    hide_entity: True
    trigger:
      - platform: state
        entity_id: binary_sensor.bedtime_switch
        state: 'on'
    action:
      service: script.turn_on
      entity_id: script.brendans_bedroom_automate_leaving
      
media_player:
  - platform: roku
    host: 192.168.11.162
  - platform: kodi
    host: 192.168.11.164
  - platform: cast
    host: 192.168.11.14

shell_command: !include shell_commands.yaml
camera:
  - platform: rpi_camera
    name: Fire Camera
    image_width: 640  
    image_height: 480  
    image_quality: 7  
    image_rotation: 0  
    timelapse: 1000  
    horizontal_flip: 0  
    vertical_flip: 0  
    file_path: /home/hass/picamera/image.jpg 
    
    
    # Enables the frontend
frontend:

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Show links to resources in log and frontend
#introduction:

# Weather Prediction
#sensor:
#  platform: yr
