# - platform: mqtt
  # name: "Brendan Bedroom TV Power"
  # state_topic: "/media/brendanbedroom/tv/power/status"
  # command_topic: "/media/brendanbedroom/tv/power/set"
  # payload_on: "ON"
  # payload_off: "OFF"
  # optimistic: false
  # qos: 0
  # retain: true

# - platform: mqtt
  # name: "Jordan Fireplace Monitor"
  # state_topic: "/fireplace/monitors/jordan/status"
  # command_topic: "/fireplace/monitors/jordan/set"
  # payload_on: "ON"
  # payload_off: "OFF"
  # optimistic: true
  # qos: 0
  # retain: true
# - platform: mqtt
  # name: "Brendan Fireplace Monitor"
  # state_topic: "/fireplace/monitors/brendan/status"
  # command_topic: "/fireplace/monitors/brendan/set"
  # payload_on: "ON"
  # payload_off: "OFF"
  # optimistic: true
  # qos: 0
  # retain: true
# - platform: mqtt
  # name: "Joel Fireplace Monitor"
  # state_topic: "/fireplace/monitors/joel/status"
  # command_topic: "/fireplace/monitors/joel/set"
  # payload_on: "ON"
  # payload_off: "OFF"
  # optimistic: true
  # qos: 0
  # retain: true

# - platform: mqtt
  # name: "Kitchen Fan"
  # state_topic: "/fireplace/fan/kitchen/status"
  # command_topic: "/fireplace/fan/kitchen/set"
  # payload_on: "ON"
  # payload_off: "OFF"
  # optimistic: false
  # qos: 0
  # retain: true




- platform: mqtt
  name: "Brendan Desk Left Monitor"
  state_topic: "/office/smartswitch/status/0"
  command_topic: "/office/smartswitch/set/0"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 0
  retain: true
- platform: mqtt
  name: "Brendan Desk Right Monitor"
  state_topic: "/office/smartswitch/status/1"
  command_topic: "/office/smartswitch/set/1"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 0
  retain: true
- platform: mqtt
  name: "Brendan Desk Center Monitor"
  state_topic: "/office/smartswitch/status/2"
  command_topic: "/office/smartswitch/set/2"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 0
  retain: true
- platform: mqtt
  name: "Aux 1"
  state_topic: "/office/smartswitch/status/3"
  command_topic: "/office/smartswitch/set/3"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 0
  retain: true
- platform: mqtt
  name: "Aux 2"
  state_topic: "/office/smartswitch/status/4"
  command_topic: "/office/smartswitch/set/4"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 0
  retain: true
- platform: mqtt
  name: "Speakers"
  state_topic: "/office/smartswitch/status/5"
  command_topic: "/office/smartswitch/set/5"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 0
  retain: true
- platform: mqtt
  name: "Soldering Station"
  state_topic: "/office/smartswitch/status/6"
  command_topic: "/office/smartswitch/set/6"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 0
  retain: true
- platform: mqtt
  name: "Power Supply"
  state_topic: "/office/smartswitch/status/7"
  command_topic: "/office/smartswitch/set/7"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: true
  qos: 0
  retain: true
