# - platform: mqtt
  # name: "Brendan Bedroom TV Power"
  # state_topic: "/media/brendanbedroom/tv/power/status"
  # command_topic: "/media/brendanbedroom/tv/power/set"
  # payload_on: "ON"
  # payload_off: "OFF"
  # optimistic: false
  # qos: 0
  # retain: true 
  
# - platform: mqtt
  # name: "Jordan Fireplace Monitor"
  # state_topic: "/fireplace/monitors/jordan/status"
  # command_topic: "/fireplace/monitors/jordan/set"
  # payload_on: "ON"
  # payload_off: "OFF"
  # optimistic: true
  # qos: 0
  # retain: true 
# - platform: mqtt
  # name: "Brendan Fireplace Monitor"
  # state_topic: "/fireplace/monitors/brendan/status"
  # command_topic: "/fireplace/monitors/brendan/set"
  # payload_on: "ON"
  # payload_off: "OFF"
  # optimistic: true
  # qos: 0
  # retain: true
# - platform: mqtt
  # name: "Joel Fireplace Monitor"
  # state_topic: "/fireplace/monitors/joel/status"
  # command_topic: "/fireplace/monitors/joel/set"
  # payload_on: "ON"
  # payload_off: "OFF"
  # optimistic: true
  # qos: 0
  # retain: true 
  
# - platform: mqtt
  # name: "Kitchen Fan"
  # state_topic: "/fireplace/fan/kitchen/status"
  # command_topic: "/fireplace/fan/kitchen/set"
  # payload_on: "ON"
  # payload_off: "OFF"
  # optimistic: false
  # qos: 0
  # retain: true 

  
  
  
- platform: mqtt
  name: "Office Center Monitor"
  state_topic: "/brendanoffice/powerstrip/switch1/status"
  command_topic: "/brendanoffice/powerstrip/switch1/set"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 0
  retain: true 
- platform: mqtt
  name: "Office Lenovo Desktop"
  state_topic: "/brendanoffice/powerstrip/switch2/status"
  command_topic: "/brendanoffice/powerstrip/switch2/set"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 0
  retain: true 
- platform: mqtt
  name: "Office Speakers"
  state_topic: "/brendanoffice/powerstrip/switch3/status"
  command_topic: "/brendanoffice/powerstrip/switch3/set"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 0
  retain: true 
- platform: mqtt
  name: "HDMI Switch"
  state_topic: "/brendanoffice/powerstrip/switch4/status"
  command_topic: "/brendanoffice/powerstrip/switch4/set"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 0
  retain: true 
- platform: mqtt
  name: "Office Left Monitor"
  state_topic: "/brendanoffice/powerstrip/switch5/status"
  command_topic: "/brendanoffice/powerstrip/switch5/set"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 0
  retain: true 
- platform: mqtt
  name: "Office Right Monitor"
  state_topic: "/brendanoffice/powerstrip/switch6/status"
  command_topic: "/brendanoffice/powerstrip/switch6/set"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 0
  retain: true 
- platform: mqtt
  name: "Office HP Desktop"
  state_topic: "/brendanoffice/powerstrip/switch7/status"
  command_topic: "/brendanoffice/powerstrip/switch7/set"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 0
  retain: true 
- platform: mqtt
  name: "ESD Strip"
  state_topic: "/brendanoffice/powerstrip/switch8/status"
  command_topic: "/brendanoffice/powerstrip/switch8/set"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 0
  retain: true 